version: '3'

services:
  db:
    image: docker.io/library/postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=robin
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      context: ./Backend/backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 7 --worker-class gevent --timeout 180
    #command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code
      - ./data/media:/media
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=robin
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nginx:
    build: ./nginx
    image: evgeniy-khyst/nginx
    environment:
      - DRY_RUN
    volumes:
      - ./config.json:/letsencrypt-docker-compose/config.json:ro
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-conf/conf.d:/etc/nginx/conf.d:ro
      - ./html:/var/www/html:ro
      - nginx_conf_ssl:/etc/nginx/ssl
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: [ "CMD", "nc", "-z", "nginx", "80" ]
      interval: 30s
      timeout: 30s
      start_period: 30s
      retries: 10
    restart: unless-stopped

  certbot:
    build: ./certbot
    image: evgeniy-khyst/certbot
    environment:
      - DRY_RUN
    volumes:
      - ./config.json:/letsencrypt-docker-compose/config.json:ro
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
    healthcheck:
      test: [ "CMD-SHELL", 'test -n "$$(ls -A /etc/letsencrypt/live/)" || test "$$DRY_RUN" == "true" || exit 1' ]
      interval: 30s
      timeout: 30s
      start_period: 30s
      retries: 5
    depends_on:
      nginx:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend/frontend
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=na-mahlzeit.de,www.na-mahlzeit.de
      - LETSENCRYPT_HOST=na-mahlzeit.de,www.na-mahlzeit.de
      - LETSENCRYPT_EMAIL=fuerRo138@gmx.de
    depends_on:
      - backend

volumes:
  nginx_conf_ssl:
  letsencrypt_certs:
  certbot_acme_challenge:
  db-volume:
