version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: robin
      POSTGRES_PASSWORD: postgres

  backend:
    image: python:3
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
